version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=DEV
      - HOST=0.0.0.0
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "8010:8000"
    depends_on:
      - redis
    command: python hello.py
    image: johnsami/dockerized-app-build-app:latest
  redis:
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"
